In [21]:
import numpy as np

In [22]:
"""
NumPy Array Attributes
"""
print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [37]:
# Random number generator
np.random.seed(0)
arr1 = np.random.randint(10,size=6)
print(arr1)
arr2 = np.random.randint(10,size=(3,4))
print(arr2)
arr3 = np.random.randint(10,size=(3,4,5))
print(arr3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [39]:
# Attributes
print(arr2)
print("arr2.ndim =", arr2.ndim)
print("arr2.shape =", arr2.shape)
print("arr2.size =", arr2.size)
print("arr2.dtype =", arr2.dtype)
print("arr2.itemsize =", arr2.itemsize)
print("arr2.nbytes =", arr2.nbytes)


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
arr2.ndim = 2
arr2.shape = (3, 4)
arr2.size = 12
arr2.dtype = int32
arr2.itemsize = 4
arr2.nbytes = 48


In [40]:
"""
Slicing
"""
arr = np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [42]:
# Multi-dimensional Subarrays
np.random.seed(0)
arr = np.random.randint(10,size=(6,8))
print(arr)

arr_sub = arr[3:5, 4:7]
print(arr_sub)

[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]]
[[5 0 2]
 [3 7 0]]


In [45]:
"""
Subarrys as no-copy views
"""
np.random.seed(0)
arr = np.random.randint(10,size=(3,4))
print(arr,'\n')

arr_sub = arr[:2,:2]
print(arr_sub,'\n')

arr_sub[0,0] = 99
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[[5 0]
 [7 9]] 

[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [49]:
# copy()

arr=np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
print(arr)

arr_sub = arr[:2,:2].copy()
print(arr_sub,'\n')

arr_sub[0,0] = 99
print(arr_sub)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[12  5]
 [ 7  6]] 

[[99  5]
 [ 7  6]]


In [52]:
# np.newaxis
arr = np.array([1,2,3])
print(arr)
print("arr.ndim =",arr.ndim)
print("arr.shape =",arr.shape)

arr_new = arr[:, np.newaxis]
print(arr_new)
print("arr.ndim =",arr.ndim)
print("arr.shape =",arr.shape)

[1 2 3]
arr.ndim = 1
arr.shape = (3,)
[[1]
 [2]
 [3]]
arr.ndim = 1
arr.shape = (3,)


In [61]:
"""
Array Concatenation
"""

arr_1 = np.array([[1,2,3],[1,2,3]])
arr_2 = np.array([[4,5,6],[4,5,6]])
arr_3 = np.array([[7,8,9],[7,8,9]])

arr_total = np.concatenate([arr_1,arr_2,arr_3],axis=0)
print(arr_total)

arr_total = np.vstack([arr_1,arr_2,arr_3])
print(arr_total,'\n')

arr_total = np.hstack([arr_1,arr_2,arr_3])
print(arr_total,'\n')

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]] 

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]] 



In [62]:
"""
Array Splitting
"""

arr = [1,2,3,99,99,3,2,1]
print(arr,'\n')

arr_1,arr_2,arr_3 = np.split(arr,[3,5])
print(arr_1,arr_2,arr_3)

[1, 2, 3, 99, 99, 3, 2, 1] 

[1 2 3] [99 99] [3 2 1]
