In [3]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [9]:
# Creating a NumPy Array
lst = [1.5,"string",True]

arr = np.array(lst)
print(arr)

['1.5' 'string' 'True']


In [10]:
# .dtype attribute
print(arr.dtype)

<U32


In [19]:
"""
Size Comparison of ndarrary and list objects
"""
from sys import getsizeof

lst = [1,2,3,4,5,6,7,8,9,10,11,12]
print(getsizeof(lst))

arr = np.array(lst)
print(getsizeof(arr))

152
152


In [23]:
"""
Operations with NumPy Arrays
"""
prices = [30,25,40,20,20,35,50,35]
new_price = [price-5 for price in prices]
print(prices)
print(new_price)

prices_arr = np.array(prices)
prices_arr -= 5
print(prices_arr)


[30, 25, 40, 20, 20, 35, 50, 35]
[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [38]:
"""
Exercise: Test Scores
"""
test_1 = np.array([92,94,88,91,87])
test_2 = np.array([79,100,86,93,91])
test_3 = np.array([87,85,72,90,92])

test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3
print(total_grade)
final_grade = total_grade / 3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_adwoa_test_1)

student_scores = np.array([test_1,test_2,test_3])
print(student_scores)

print(student_scores[2,0])

print(student_scores[:,4])

[89 87 74 92 94]
[258 279 246 274 270]
[86.         93.         82.         91.33333333 90.        ]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [44]:
"""
Logical Operations with Arrays
"""

a=np.array([10,2,2,4,5,3,9,8,9,7])
mask = a > 5
print(mask)

selected = a[a > 5]
print(selected)

selected = a[(a > 6) | (a < 4)]
print(selected)

selected = a[(a > 4) & (a < 8)]
print(selected)


[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
[5 7]


In [60]:
"""
Exercise: Goldilocks Porridge Festival
"""

porridge = [79,65,50,63,56,90,85,98,79,51]
porridge_arr = np.array([79,65,50,63,56,90,85,98,79,51])

print(porridge)
print(porridge_arr)

cold = porridge_arr[porridge_arr < 60] # 60도 미만 = 59도 이하
print(cold)

hot = porridge_arr[porridge_arr > 80] # 80도 초과 = 81도 이상
print(hot)

just_right = porridge_arr[(porridge_arr >= 60) & (porridge_arr <= 80)] # 60~80 포함
print(just_right)

[79, 65, 50, 63, 56, 90, 85, 98, 79, 51]
[79 65 50 63 56 90 85 98 79 51]
[50 56 51]
[90 85 98]
[79 65 63 79]
