In [37]:
import numpy as np

In [76]:
"""
Computering reciprocals in loops
"""

# Function for computuring reciprocals using Looping
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

np.random.seed(0)
values = np.random.randint(1,10,size=5)
print(values)

[6 1 4 4 8]


In [77]:
"""
Comparison: Loop vs ufuncs(vectorized)
"""
big_array = np.random.randint(1, 100, size=1000000)

# Looping on a big array

# jupyter magic function
%timeit compute_reciprocals(big_array)

1.47 s ± 45 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [78]:
# Vectorzied operations
%timeit 1 / big_array

2.71 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [30]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)
print(arr1, arr2)

arr1= arr1 - 2
print(arr1, arr2)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size=(3,5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2] [0 1 7 6 9]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [33]:
"""
UFuncs: Absolute Value
"""

x = np.array([-2,-1,0,1,2])
print(np.abs(x))

x = np.array([3-4j, 4-3j,2+0j,0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [44]:
"""
UFuncs: Trigonomtric Functions
"""

theta = np.linspace(0,np.pi,3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

x = np.linspace(0,100,10)
print(x)

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [53]:
"""
UFuncs: Aggregation
"""

x = np.arange(1,5)
print(x)
aggr = np.add.reduce(x)
print(aggr)
aggr = np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [58]:
# accumulate()
print(x)

accum = np.add.accumulate(x)
print(accum)

accum = np.multiply.accumulate(x)
print(accum)

[1 2 3 4]
[ 1  3  6 10]
[ 1  2  6 24]


In [60]:
# Summing the Volues in on Aarray

np.random.seed(3)
arr = np.random.rand(1000000)

print(arr)
print("sum =", np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum = 500422.19897015305


In [62]:
%timeit sum(arr)

60.2 ms ± 3.52 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [65]:
%timeit np.sum(arr) 

696 µs ± 22 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [68]:
# Other Aggr. functions

print(("max ="), np.max(arr))
print(("min ="), np.min(arr))
print(("mean ="), np.mean(arr))
print(("median ="), np.median(arr))
print(("percentile ="), np.percentile(arr,90))

print(np.any(arr>1))
print(np.all(arr>0))

max = 0.9999996367889004
min = 1.5496004267534502e-06
mean = 0.500422198970153
median = 0.5005659265960778
percentile = 0.9001765340710965
False
True


In [73]:
# Multi dimensional aggregotes

np.random.seed(5)
arr = np.random.randint(10,size=(3,4))
print(arr)

print(np.sum(arr,axis=0)) #세로(row marginal)

print(np.sum(arr,axis=1)) #가로(column marginal)

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
[15 28  8]
